### ISSUE TITLE
cast error 

### ISSUE THREAD

**Issue by mojie126** [fortify-ps/fortify-client-api#2]
```java
		SSCAuthenticatingRestConnection sscClient = SSCAuthenticatingRestConnection.builder().userName(fortifyAccount).password(fortifyPassword).baseUrl(fortifyUrl).multiThreaded(true).build();

		SSCApplicationsQueryBuilder sscApplicationsQueryBuilder = sscClient.api(SSCApplicationAPI.class).queryApplications();
		for (Object o : sscApplicationsQueryBuilder.build().getAll()) {
//			JSONObject jsonObject = JSONUtil.parseObj(o);
//			System.out.println(jsonObject);
		}
```

err info:
```log
Exception in thread "main" java.lang.ClassCastException: com.alibaba.fastjson.JSONObject cannot be cast to com.fortify.util.rest.json.JSONMap
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getTokenData(SSCTokenFactoryUserCredentials.java:80)
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.lambda$getToken$0(SSCTokenFactoryUserCredentials.java:72)
	at com.fortify.util.log4j.LogMaskingHelper$AbstractMasker.on(LogMaskingHelper.java:105)
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getToken(SSCTokenFactoryUserCredentials.java:71)
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getTokenSynchronized(SSCTokenFactoryUserCredentials.java:65)
	at com.fortify.client.ssc.connection.SSCAuthenticatingRestConnection.updateBuilder(SSCAuthenticatingRestConnection.java:85)
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:242)
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequestWithFinalizedWebTarget(AbstractRestConnection.java:210)
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:200)
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:187)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.executeRequest(AbstractRestConnectionQuery.java:143)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processSingleRequest(AbstractRestConnectionQuery.java:217)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:207)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:89)
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.getAll(AbstractRestConnectionQuery.java:109)
	at com.wocnm.controller.TEST.main(TEST.java:37)
```

**Comment by rsenden** [comment]
I have removed the explicit cast in the 5.6-SNAPSHOT branch; the code now depends on Spring's ConversionService to get a JSONMap instance from the parent map. However most likely there is no appropriate converter registered, so you will now probably just run into another exception.

The client API library converts all SSC response data into JSONMap (or JSONList) instances, which are basically just regular Maps/Lists but with some JSON-specific functionality. Apparently, if there is another JSON library on the classpath, the root object will still be converted into a JSONMap, but any child-objects inside that map are being converted into the JSON representation provided by that library; com.alibaba.fastjson.JSONObject in your case.

The main purpose of the Fortify client API library is to provide connectivity for other projects on https://github.com/fortify-ps. Although anyone is free to re-use this open-source library, it is not meant as a general-purpose client, and doesn't come with any support. With this in mind, also note that newer version of the library may not be backward-compatible with older versions.

As such, you will either need to accept the limitations of this library (and thus remove any other JSON libraries from the classpath), or look for an alternative solution. For example, you can invoke the Fortify REST API directly using any generic REST client library, or you could use the Swagger-generated client at https://github.com/fortify/ssc-restapi-client.

**Comment by mojie126** [comment]
I got the token through other methods, but the following code rewrites the correct token again
```java
	public SSCTokenFactoryTokenCredentials(String token) {
		this.token = Base64.encodeBase64String(token.getBytes());
	}
```

**Comment by mojie126** [comment]
> I got the token through other methods, but the following code rewrites the correct token again
> 
> ```java
> 	public SSCTokenFactoryTokenCredentials(String token) {
> 		this.token = Base64.encodeBase64String(token.getBytes());
> 	}
> ```

It has been solved. I will restore the token to the state before Base64
