### ISSUE TITLE
Failed to convert from type [java.lang.String] to type [java.util.Date] 

### ISSUE THREAD

**Issue by ghost** [fortify-ps/fortify-client-api#5]
{"data":{"id":229,"token":"[hidden]","creationDate":"2021-03-24T20:35:20.052+0000","terminalDate":"2021-03-25T20:35:20.052+0000","remainingUsages":-1,"type":"UnifiedLoginToken","description":null,"username":"XXXXXXXXX"},"responseCode":200}

2021-03-24 13:35:20,114 [main] ERROR com.fortify.processrunner.RunProcessRunnerFromCLI - [Process] Error processing
org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.util.Date] for value '2021-03-25T20:35:20.052+0000'; nested exception is java.time.format.DateTimeParseException: Text '2021-03-25T20:35:20.052+0000' could not be parsed, unparsed text found at index 22
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:191) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.json.JSONMap.get(JSONMap.java:132) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getTokenData(SSCTokenFactoryUserCredentials.java:81) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.lambda$getToken$0(SSCTokenFactoryUserCredentials.java:72) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.log4j.LogMaskingHelper$AbstractMasker.on(LogMaskingHelper.java:105) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.client.ssc.connection.SSCTokenFactoryUserCredentials.getToken(SSCTokenFactoryUserCredentials.java:71) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.client.ssc.connection.SSCAuthenticatingRestConnection.updateBuilder(SSCAuthenticatingRestConnection.java:86) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:207) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequestWithFinalizedWebTarget(AbstractRestConnection.java:175) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:165) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.connection.AbstractRestConnection.executeRequest(AbstractRestConnection.java:152) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.executeRequest(AbstractRestConnectionQuery.java:138) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processSingleRequest(AbstractRestConnectionQuery.java:207) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:197) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.processAll(AbstractRestConnectionQuery.java:87) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.query.AbstractRestConnectionQuery.getAll(AbstractRestConnectionQuery.java:107) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.bugtracker.common.src.context.AbstractSourceContextGenerator.generateContexts(AbstractSourceContextGenerator.java:180) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.getContexts(RunProcessRunnerFromSpringConfig.java:151) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromSpringConfig.run(RunProcessRunnerFromSpringConfig.java:81) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromCLI.run(RunProcessRunnerFromCLI.java:166) [FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.processrunner.RunProcessRunnerFromCLI.main(RunProcessRunnerFromCLI.java:359) [FortifyBugTrackerUtility-4.1.jar:?]
Caused by: java.time.format.DateTimeParseException: Text '2021-03-25T20:35:20.052+0000' could not be parsed, unparsed text found at index 22
	at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source) ~[?:1.8.0_281]
	at java.time.format.DateTimeFormatter.parseBest(Unknown Source) ~[?:1.8.0_281]
	at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.parseZonedDateTime(JSONConversionServiceFactory.java:72) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.parseDate(JSONConversionServiceFactory.java:68) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.convert(JSONConversionServiceFactory.java:64) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at com.fortify.util.rest.json.JSONConversionServiceFactory$DateConverter.convert(JSONConversionServiceFactory.java:61) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:385) ~[FortifyBugTrackerUtility-4.1.jar:?]
	at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41) ~[FortifyBugTrackerUtility-4.1.jar:?]
	... 22 more

**Comment by rsenden** [comment]
This was already fixed in commit 14423fe72e2bb20880777d5365f56793ea5a66ae, but not all integrations have been updated yet to include this fix. For example, FortifyBugTrackerUtility 4.1 doesn't have this fix yet but will have the fix when the next version is released.
